# config/packages/knp_paginator.yaml
knp_paginator:
    template:
        pagination: 'pagination/custom_pagination.html.twig' # Path to your custom pagination template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Optional: Customize sortable links