security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            logout:
                path: app_logout
                target: /
            # Remove the form_login since we are using a custom authenticator
    access_control:
        # Public pages (accessible without authentication)
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/parentsignup, roles: PUBLIC_ACCESS }
        - { path: ^/pageacceuil, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS } 
        - { path: ^/reset, roles: PUBLIC_ACCESS } 
        - { path: ^/send, roles: PUBLIC_ACCESS }
        - { path: ^/update-password, roles: PUBLIC_ACCESS } 
        - { path: ^/quizz2, roles: PUBLIC_ACCESS } 
        - { path: ^/suggestion2, roles: PUBLIC_ACCESS }
        - { path: ^/quizz/average, roles: PUBLIC_ACCESS }  
        - { path: ^/question2, roles: ROLE_TEACHER }
        - { path: ^/cours, roles: PUBLIC_ACCESS}
       
        

        # Pages accessible by ROLE_TEACHER and ROLE_PARENT
        - { path: ^/quizz/average, roles: [ROLE_TEACHER, ROLE_Parent] }
        - { path: ^/chapitre, roles: ROLE_TEACHER }
        
        
        
        # Pages accessible only by ROLE_ADMIN
        - { path: ^/listusers, roles: ROLE_ADMIN }
        - { path: ^/paiement/stats, roles: ROLE_ADMIN }

        # Pages accessible by all authenticated users (any role)
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/user/edit, roles: IS_AUTHENTICATED_FULLY }

       
