security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            logout:
                path: app_logout
                target: /
    access_control:
        - { path: ^/api/translate, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/articles/with-comments, roles: PUBLIC_ACCESS }
        - { path: ^/api/articles/search, roles: PUBLIC_ACCESS }
        - { path: ^/api/articles/\d+/stats, roles: PUBLIC_ACCESS }
        - { path: ^/api/recent-activity, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
