twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        ckeditor_enable: true

when@test:
    twig:
        strict_variables: true
