vich_uploader:
    db_driver: orm
    mappings:
        cours_files:
            uri_prefix: /uploads/cours_files
            upload_destination: '%kernel.project_dir%/public/uploads/cours_files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: Vich\UploaderBundle\Naming\ConfigurableDirectoryNamer
