controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_participation:
    path: /participation/{id}
    controller: App\Controller\ParticipationController::register