<<<<<<< HEAD
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
=======
>>>>>>> 569ed047865299fc8826d7c0b415cb15f7d296ef
parameters:
    events_images_directory: '%kernel.project_dir%/public/uploads/events'
    locale: 'fr'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
<<<<<<< HEAD
    # this creates a service per class whose id is the fully-qualified class name
=======
>>>>>>> 569ed047865299fc8826d7c0b415cb15f7d296ef
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

<<<<<<< HEAD
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
=======
    # Ajouter le service StripeService
    App\Service\StripeService:
        arguments:
            $secretKey: '%env(STRIPE_SECRET_KEY)%'
            $webhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'
  



>>>>>>> 569ed047865299fc8826d7c0b415cb15f7d296ef
